### ISSUE TITLE
Improve melee attacks

### ISSUE THREAD

**Issue by jamesmitchellwest** [jamesmitchellwest/Astoria-Legend-Game#12]
Need to be able to punch while jumping.

Need to think about how were going to handle collision.  Currently the attacking sprite doesn't really extend out much past the player hitbox.  Should we make the player lunge forward when punching?  When crouch attacking should we turn it into a slide attack?

**Comment by jwest6** [comment]
@jamesmitchellwest Metal Gear sticks out the fist and essentially extends the hit to the width of the body in front of your character. That was always a tough HTH battle though. Maybe a punch one block out and a roundhouse kick 1.5? These would all be more animation frames. What about a whip? Donatello's bo in TMNT 1 is pretty dope too. I always like extended weapons. Double Dragon helicopter kick would also be rad.

**Comment by B-Swayze** [comment]
I vote yes on slide attack.  Not only as an attack, but as a strategy to slide under blocks and such.  

I'm up for a design challenge if we want to create a dope aerial attack or add projectiles to the current animation.

**Comment by jamesmitchellwest** [comment]
I like the whip idea but I could swing out a microphone attached to the mic cable .  @B-Swayze,  you could redo your keytar animation so it extends out past the body.  Make them extend out the same distance. Yay? Nay?

**Comment by B-Swayze** [comment]
@jamesmitchellwest since it would extend past the sprite width, I think the mic would be its own object, with its own hit properties-- right?  Or is there a better way to go about it?
Im imagining it working similar to slimers proton beam.

I can modify the sprite for my character's attack.  How big of a pain in the ass is it if we have different attack properties for each character?  If it's _not_ a big deal, it might be another cool strategic element to choosing a character...

**Comment by jamesmitchellwest** [comment]
It could be a separate entity or i could just add a shape to the player body that only interacts while attacking. Im not too sure on the pros and cons of either method

**Comment by B-Swayze** [comment]
Thoughts?

![Mic-Throw](https://user-images.githubusercontent.com/83519130/117062967-c527a800-ace9-11eb-8087-e57e825459cf.gif)

**Comment by jamesmitchellwest** [comment]
Axing melee
